### PR TITLE
chore: Update to layer 111

### PR DESCRIPTION
**Pull request by SchemaBot**
Hello! It's time... time to update the schema layer! This pull request migrates from layer 109 to layer 111. Please check to make sure I didn't screw anything up!

### New constructors
- inputMediaDice
- messageMediaDice
- updateMessagePollVote
- updateDialogFilter
- updateDialogFilterOrder
- updateDialogFilters
- inputStickerSetDice
- keyboardButtonRequestPoll
- messageEntityBankCard
- peerSelfLocated
- messageUserVote
- messageUserVoteMultiple
- messageUserVoteInputOption
- messages.votesList
- bankCardOpenUrl
- payments.bankCardData
- dialogFilter
- dialogFilterSuggested
- statsDateRangeDays
- statsAbsValueAndPrev
- statsPercentValue
- statsGraphError
- statsGraphAsync
- statsGraph
- stats.broadcastStats
- messageInteractionCounters

### New methods
- messages.getPollVotes
- messages.toggleStickerSets
- messages.getDialogFilters
- messages.getSuggestedDialogFilters
- messages.updateDialogFilter
- messages.updateDialogFiltersOrder
- payments.getBankCardData
- stats.loadAsyncGraph
- stats.getBroadcastStats

Documentation files were created for these new constructors and methods.

With ❤️,
Your Friendly Neighborhood Schemabot

### CODE REVIEW

**Comment by tjhorner** [comment]
wow this sucks why are there merge conflicts

**Comment by tjhorner** [comment]
oh god damn it, I see what went wrong...

**Comment by tjhorner** [comment]
fuck I'll fix this later, it's missing a commit from master

**Comment by mockup568** [comment]
tj, looks like you're talking alone ! Just wanted to let you know I'm here and you have a listener !! :-)
And BTW, you should subscribe to receive Brave browser tips !

**Comment by tjhorner** [comment]
@mdhak83 thanks lol

moved to #28

**Pull request closed without merging**
